version: 0.0
os: linux
files:
  - source: index.php
    destination: /var/www/html
permissions:
  - object: /var/www/html/index.php
    owner: ec2-user
    group: ec2-user
    mode: 644
hooks:
  BeforeInstall:
    - location: scripts/beforeinstall.sh
      timeout: 180